Repository CharmRoom/CharmRoom-Back, pull requests merged in 2024-08, with the labels that each got.

#149 Refactor/#147 dy
  src/main/java/com/charmroom/charmroom/config/SecurityConfig.java
  src/main/java/com/charmroom/charmroom/controller/api/AdminController.java
  src/main/java/com/charmroom/charmroom/controller/api/AuthController.java
  src/main/java/com/charmroom/charmroom/controller/api/BoardController.java
  src/main/java/com/charmroom/charmroom/controller/api/CommentController.java
  src/main/java/com/charmroom/charmroom/controller/api/UserController.java
  src/main/java/com/charmroom/charmroom/dto/business/ClubMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentDto.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentLikeMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/UserMapper.java
  src/main/java/com/charmroom/charmroom/dto/presentation/BoardDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/CommentDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/CommentLikeDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/PointDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/UserDto.java
  src/main/java/com/charmroom/charmroom/dto/validation/BoardTypeValidator.java
  src/main/java/com/charmroom/charmroom/dto/validation/PointTypeValidator.java
  src/main/java/com/charmroom/charmroom/dto/validation/ValidBoardType.java
  src/main/java/com/charmroom/charmroom/dto/validation/ValidPointType.java
  src/main/java/com/charmroom/charmroom/security/JWTFilter.java
  src/main/java/com/charmroom/charmroom/service/BoardService.java
  src/main/java/com/charmroom/charmroom/service/CommentService.java
  src/main/java/com/charmroom/charmroom/service/PointService.java
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/test/java/com/charmroom/charmroom/controller/integration/AdminControllerIntegrationTestDy.java
  src/test/java/com/charmroom/charmroom/controller/integration/AuthControllerIntegrationTestDy.java
Labels: ✨ Feature, 🔨 Refactor

#150 Refactor/#148 refactoring, dto validation cm
  src/main/java/com/charmroom/charmroom/controller/api/AdminController.java
  src/main/java/com/charmroom/charmroom/controller/api/ArticleController.java
  src/main/java/com/charmroom/charmroom/controller/api/ClubController.java
  src/main/java/com/charmroom/charmroom/controller/api/MarketController.java
  src/main/java/com/charmroom/charmroom/controller/api/UserController.java
  src/main/java/com/charmroom/charmroom/dto/business/AdMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/ClubMapper.java
  src/main/java/com/charmroom/charmroom/dto/presentation/AdDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/ArticleDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/ClubDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/MarketDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/SubscribeDto.java
  src/main/java/com/charmroom/charmroom/service/AdService.java
  src/main/java/com/charmroom/charmroom/service/ArticleLikeService.java
  src/main/java/com/charmroom/charmroom/service/ArticleService.java
  src/main/java/com/charmroom/charmroom/service/ClubRegisterService.java
  src/main/java/com/charmroom/charmroom/service/ClubService.java
  src/main/java/com/charmroom/charmroom/service/MarketService.java
  src/main/java/com/charmroom/charmroom/service/SubscribeService.java
  src/main/java/com/charmroom/charmroom/service/WishService.java
  src/test/java/com/charmroom/charmroom/controller/integration/ArticleControllerIntegrationTestCm.java
  src/test/java/com/charmroom/charmroom/controller/integration/ClubControllerIntegrationTestCm.java
  src/test/java/com/charmroom/charmroom/controller/integration/MarketControllerIntegrationTestCm.java
  src/test/java/com/charmroom/charmroom/controller/integration/UserControllerIntegrationTestCm.java
  src/test/java/com/charmroom/charmroom/controller/unit/AdminControllerUnitTestCm.java
  src/test/java/com/charmroom/charmroom/controller/unit/ArticleControllerUnitTestCm.java
  src/test/java/com/charmroom/charmroom/controller/unit/ClubControllerUnitTestCm.java
  src/test/java/com/charmroom/charmroom/controller/unit/MarketControllerUnitTestCm.java
  src/test/java/com/charmroom/charmroom/controller/unit/UserControllerUnitTestCm.java
  src/test/java/com/charmroom/charmroom/repository/AdRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ArticleLikeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ArticleRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ClubRegisterRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ClubRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/MarketRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/SubscribeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/WishRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/service/AdServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ArticleLikeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ArticleServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ClubRegisterServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ClubServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/MarketServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/SubscribeServiceUnitTest.java
Labels: 🔨 Refactor

#151 Feat/#37 JWT Refresh token
  build.gradle
  src/main/java/com/charmroom/charmroom/config/RedisConfig.java
  src/main/java/com/charmroom/charmroom/config/SecurityConfig.java
  src/main/java/com/charmroom/charmroom/controller/api/AuthController.java
  src/main/java/com/charmroom/charmroom/controller/api/BoardController.java
  src/main/java/com/charmroom/charmroom/dto/business/TokenDto.java
  src/main/java/com/charmroom/charmroom/dto/presentation/PointDto.java
  src/main/java/com/charmroom/charmroom/entity/RefreshToken.java
  src/main/java/com/charmroom/charmroom/exception/BusinessLogicError.java
  src/main/java/com/charmroom/charmroom/repository/RefreshTokenRepository.java
  src/main/java/com/charmroom/charmroom/security/JWTFilter.java
  src/main/java/com/charmroom/charmroom/security/JWTUtil.java
  src/main/java/com/charmroom/charmroom/security/LoginFilter.java
  src/main/java/com/charmroom/charmroom/service/AuthService.java
  src/main/java/com/charmroom/charmroom/service/BoardService.java
  src/test/java/com/charmroom/charmroom/controller/integration/AuthControllerIntegrationTestDy.java
Labels: ✨ Feature

#153 setting: CICD script
  .github/workflows/deploy-dev.yml
  .github/workflows/gradle.yml
Labels: ⚙ Setting, 🌏 Deploy

#156 Feat/#155 cors
  src/main/java/com/charmroom/charmroom/config/CorsConfig.java
  src/main/java/com/charmroom/charmroom/config/CorsMvcConfig.java
  src/main/java/com/charmroom/charmroom/config/SecurityConfig.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: ✨ Feature
