Repository CharmRoom/CharmRoom-Back, pull requests merged in 2024-06, with the labels that each got.

#8 Feat/#6 Entity(User, Subscribe, Board, Attachment, Comment, CommentLike, Image)
  src/main/java/com/charmroom/charmroom/entity/Attachment.java
  src/main/java/com/charmroom/charmroom/entity/Board.java
  src/main/java/com/charmroom/charmroom/entity/Comment.java
  src/main/java/com/charmroom/charmroom/entity/CommentLike.java
  src/main/java/com/charmroom/charmroom/entity/Image.java
  src/main/java/com/charmroom/charmroom/entity/Subscribe.java
  src/main/java/com/charmroom/charmroom/entity/User.java
  src/main/java/com/charmroom/charmroom/entity/embid/CommentLikeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/SubscribeId.java
  src/main/java/com/charmroom/charmroom/entity/enums/AttachmentType.java
  src/main/java/com/charmroom/charmroom/entity/enums/BoardType.java
  src/main/java/com/charmroom/charmroom/entity/enums/UserLevel.java
Labels: ✨ Feature

#10 setting: CI Github workflow
  .github/workflows/gradle.yml
Labels: ⚙ Setting

#12 feat/#11 Point Entity
  src/main/java/com/charmroom/charmroom/entity/Point.java
  src/main/java/com/charmroom/charmroom/entity/enums/PointType.java
Labels: ✨ Feature

#18 Feat/#17 엔티티 마무리 및 리팩토링
  .github/workflows/gradle.yml
  src/main/java/com/charmroom/charmroom/entity/Ad.java
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/entity/ArticleLike.java
  src/main/java/com/charmroom/charmroom/entity/Attachment.java
  src/main/java/com/charmroom/charmroom/entity/Club.java
  src/main/java/com/charmroom/charmroom/entity/Market.java
  src/main/java/com/charmroom/charmroom/entity/Point.java
  src/main/java/com/charmroom/charmroom/entity/User.java
  src/main/java/com/charmroom/charmroom/entity/Wish.java
  src/main/java/com/charmroom/charmroom/entity/embid/ArticleLikeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/SubscribeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/WishId.java
Labels: ✨ Feature, 🔨 Refactor

#21 feat: Article Comment 연관관계
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/entity/Comment.java
Labels: ✨ Feature

#22 Feat/#19 Authentication
  build.gradle
  src/main/java/com/charmroom/charmroom/SecurityConfig.java
  src/main/java/com/charmroom/charmroom/entity/enums/UserLevel.java
  src/main/java/com/charmroom/charmroom/form/SignupForm.java
  src/main/java/com/charmroom/charmroom/repository/UserRepository.java
  src/main/java/com/charmroom/charmroom/service/UserSecurityService.java
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/main/java/com/charmroom/charmroom/viewcontroller/AuthController.java
  src/main/java/com/charmroom/charmroom/viewcontroller/IndexController.java
  src/main/resources/templates/form_errors.html
  src/main/resources/templates/login_form.html
  src/main/resources/templates/signup_form.html
Labels: ✨ Feature

#27 Feat/#26 Edit CICD
  .github/workflows/deploy-dev.yml
  .github/workflows/gradle.yml
Labels: ⚙ Setting

#28 chore: Update .gitignore
  .gitignore
Labels: ⚙ Setting

#29 Feat/#24 repo dongyeop
  build.gradle
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/entity/Attachment.java
  src/main/java/com/charmroom/charmroom/entity/Board.java
  src/main/java/com/charmroom/charmroom/entity/Comment.java
  src/main/java/com/charmroom/charmroom/entity/CommentLike.java
  src/main/java/com/charmroom/charmroom/entity/Image.java
  src/main/java/com/charmroom/charmroom/entity/Point.java
  src/main/java/com/charmroom/charmroom/entity/User.java
  src/main/java/com/charmroom/charmroom/entity/embid/CommentLikeId.java
  src/main/java/com/charmroom/charmroom/repository/ArticleRepository.java
  src/main/java/com/charmroom/charmroom/repository/AttachmentRepository.java
  src/main/java/com/charmroom/charmroom/repository/BoardRepository.java
  src/main/java/com/charmroom/charmroom/repository/ClubRepository.java
  src/main/java/com/charmroom/charmroom/repository/CommentLikeRepository.java
  src/main/java/com/charmroom/charmroom/repository/CommentRepository.java
  src/main/java/com/charmroom/charmroom/repository/ImageRepository.java
  src/main/java/com/charmroom/charmroom/repository/PointRepository.java
  src/test/java/com/charmroom/charmroom/repository/AttachmentRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/BoardRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/CommentLikeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/CommentRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ImageRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/PointRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/UserRepositoryUnitTest.java
Labels: ✨ Feature

#30 hotfix: CD script
  .github/workflows/deploy-dev.yml
Labels: 🐞 BugFix

#32 Feat/#25 repo cmleem
  src/main/java/com/charmroom/charmroom/entity/Ad.java
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/entity/ArticleLike.java
  src/main/java/com/charmroom/charmroom/entity/Club.java
  src/main/java/com/charmroom/charmroom/entity/Market.java
  src/main/java/com/charmroom/charmroom/entity/Subscribe.java
  src/main/java/com/charmroom/charmroom/entity/Wish.java
  src/main/java/com/charmroom/charmroom/entity/embid/ArticleLikeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/SubscribeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/WishId.java
  src/main/java/com/charmroom/charmroom/repository/AdRepository.java
  src/main/java/com/charmroom/charmroom/repository/ArticleLikeRepository.java
  src/main/java/com/charmroom/charmroom/repository/ArticleRepository.java
  src/main/java/com/charmroom/charmroom/repository/BoardReposiory.java
  src/main/java/com/charmroom/charmroom/repository/MarketRepository.java
  src/main/java/com/charmroom/charmroom/repository/SubscribeRepository.java
  src/main/java/com/charmroom/charmroom/repository/WishRepository.java
  src/test/java/com/charmroom/charmroom/repository/AdRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ArticleLikeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ArticleRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ClubRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/MarketRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/SubscribeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/WishRepositoryUnitTest.java
Labels: ✨ Feature

#31 Feat/#23 jwt
  build.gradle
  src/main/java/com/charmroom/charmroom/SecurityConfig.java
  src/main/java/com/charmroom/charmroom/apicontroller/AuthApiController.java
  src/main/java/com/charmroom/charmroom/dto/CommonResponseDto.java
  src/main/java/com/charmroom/charmroom/dto/CustomUserDetails.java
  src/main/java/com/charmroom/charmroom/dto/SignupDto.java
  src/main/java/com/charmroom/charmroom/entity/User.java
  src/main/java/com/charmroom/charmroom/entity/embid/ArticleLikeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/CommentLikeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/SubscribeId.java
  src/main/java/com/charmroom/charmroom/entity/embid/WishId.java
  src/main/java/com/charmroom/charmroom/entity/enums/UserLevel.java
  src/main/java/com/charmroom/charmroom/form/SignupForm.java
  src/main/java/com/charmroom/charmroom/repository/UserRepository.java
  src/main/java/com/charmroom/charmroom/security/JWTFilter.java
  src/main/java/com/charmroom/charmroom/security/JWTUtil.java
  src/main/java/com/charmroom/charmroom/security/LoginFilter.java
  src/main/java/com/charmroom/charmroom/security/SecurityConfig.java
  src/main/java/com/charmroom/charmroom/service/CustomUserDetailsService.java
  src/main/java/com/charmroom/charmroom/service/UserSecurityService.java
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/main/java/com/charmroom/charmroom/viewcontroller/AuthController.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/test/java/com/charmroom/charmroom/repository/AttachmentRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/CommentLikeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/CommentRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/PointRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/UserRepositoryUnitTest.java
Labels: ✨ Feature

#34 Bug/#33
  src/main/java/com/charmroom/charmroom/service/CustomUserDetailsService.java
  src/test/java/com/charmroom/charmroom/repository/ArticleLikeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ArticleRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ClubRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/MarketRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/SubscribeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/WishRepositoryUnitTest.java
Labels: 🐞 BugFix

#39 Feat/#35 Service 맡은 부분과 CharmroomUtil 작성, 그리고 이에 해당하는 테스트 작성
  src/main/java/com/charmroom/charmroom/apicontroller/AuthApiController.java
  src/main/java/com/charmroom/charmroom/controller/api/AuthApiController.java
  src/main/java/com/charmroom/charmroom/controller/api/MainController.java
  src/main/java/com/charmroom/charmroom/dto/BusinessLogicErrorResponseDto.java
  src/main/java/com/charmroom/charmroom/dto/CommonResponseDto.java
  src/main/java/com/charmroom/charmroom/dto/CustomUserDetails.java
  src/main/java/com/charmroom/charmroom/dto/SignupDto.java
  src/main/java/com/charmroom/charmroom/dto/validation/UserValidator.java
  src/main/java/com/charmroom/charmroom/dto/validation/ValidUser.java
  src/main/java/com/charmroom/charmroom/entity/Attachment.java
  src/main/java/com/charmroom/charmroom/entity/Board.java
  src/main/java/com/charmroom/charmroom/entity/Comment.java
  src/main/java/com/charmroom/charmroom/entity/CommentLike.java
  src/main/java/com/charmroom/charmroom/entity/Image.java
  src/main/java/com/charmroom/charmroom/entity/User.java
  src/main/java/com/charmroom/charmroom/exception/BusinessLogicError.java
  src/main/java/com/charmroom/charmroom/exception/BusinessLogicException.java
  src/main/java/com/charmroom/charmroom/exception/ExceptionHandlerAdvice.java
  src/main/java/com/charmroom/charmroom/repository/ArticleRepository.java
  src/main/java/com/charmroom/charmroom/repository/BoardRepository.java
  src/main/java/com/charmroom/charmroom/repository/PointRepository.java
  src/main/java/com/charmroom/charmroom/repository/UserRepository.java
  src/main/java/com/charmroom/charmroom/security/SecurityConfig.java
  src/main/java/com/charmroom/charmroom/service/AttachmentService.java
  src/main/java/com/charmroom/charmroom/service/BoardService.java
  src/main/java/com/charmroom/charmroom/service/CommentLikeService.java
  src/main/java/com/charmroom/charmroom/service/CommentService.java
  src/main/java/com/charmroom/charmroom/service/ImageService.java
  src/main/java/com/charmroom/charmroom/service/PointService.java
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/main/java/com/charmroom/charmroom/util/CharmroomUtil.java
  src/main/java/com/charmroom/charmroom/viewcontroller/AuthController.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/test/java/com/charmroom/charmroom/CharmroomApplicationTests.java
  src/test/java/com/charmroom/charmroom/repository/ArticleLikeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ArticleRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/ClubRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/CommentLikeRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/CommentRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/MarketRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/UserRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/repository/WishRepositoryUnitTest.java
  src/test/java/com/charmroom/charmroom/service/AttachmentServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/BoardServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/CommentLikeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/CommentServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/CustomUserDetailsServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ImageServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/PointServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/UserServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/util/CharmroomUtilTest.java
Labels: ✨ Feature

#40 Feat/#36 service 맡은 부분(Article, ArticleLike, Ad, Market, Wish, Subscribe, Club)과 단위테스트 작성
  src/main/java/com/charmroom/charmroom/entity/ArticleLike.java
  src/main/java/com/charmroom/charmroom/exception/BusinessLogicError.java
  src/main/java/com/charmroom/charmroom/repository/ClubRepository.java
  src/main/java/com/charmroom/charmroom/service/AdService.java
  src/main/java/com/charmroom/charmroom/service/ArticleLikeService.java
  src/main/java/com/charmroom/charmroom/service/ArticleService.java
  src/main/java/com/charmroom/charmroom/service/ClubService.java
  src/main/java/com/charmroom/charmroom/service/MarketService.java
  src/main/java/com/charmroom/charmroom/service/SubscribeService.java
  src/main/java/com/charmroom/charmroom/service/WishService.java
  src/test/java/com/charmroom/charmroom/service/AdServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ArticleLikeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ArticleServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ClubServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/MarketServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/SubscribeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/WishServiceUnitTest.java
Labels: ✨ Feature

#47 feat: Charmroom util add attachment and article relation
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/service/ArticleService.java
  src/main/java/com/charmroom/charmroom/util/CharmroomUtil.java
  src/test/java/com/charmroom/charmroom/service/ArticleServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ClubServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/util/CharmroomUtilTest.java
Labels: ✨ Feature

#49 feat: UserService 유저 생성 시 이미지 등록과 이미지 수정
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/test/java/com/charmroom/charmroom/service/UserServiceUnitTest.java
Labels: ✨ Feature

#50 [✨ Feature] #41 CharmroomUtil 수정, 서비스 코드 수정
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/service/ArticleService.java
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/main/java/com/charmroom/charmroom/util/CharmroomUtil.java
  src/test/java/com/charmroom/charmroom/service/ArticleServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ClubServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/UserServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/util/CharmroomUtilTest.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#65 feat/#61 User,Image,Point,Club service DTO and apply to User service test
  src/main/java/com/charmroom/charmroom/controller/api/AuthApiController.java
  src/main/java/com/charmroom/charmroom/dto/business/ClubDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ClubMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/ImageDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ImageMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/PointDto.java
  src/main/java/com/charmroom/charmroom/dto/business/PointMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/UserDto.java
  src/main/java/com/charmroom/charmroom/dto/business/UserMapper.java
  src/main/java/com/charmroom/charmroom/dto/presentation/SignupDto.java
  src/main/java/com/charmroom/charmroom/entity/Club.java
  src/main/java/com/charmroom/charmroom/entity/User.java
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/test/java/com/charmroom/charmroom/service/UserServiceUnitTest.java
Labels: ✨ Feature, 🔨 Refactor

#66 Feat/#62 Apply Image, Club, Point DTO to service
  src/main/java/com/charmroom/charmroom/dto/presentation/SignupDto.java
  src/main/java/com/charmroom/charmroom/service/ClubService.java
  src/main/java/com/charmroom/charmroom/service/ImageService.java
  src/main/java/com/charmroom/charmroom/service/PointService.java
  src/test/java/com/charmroom/charmroom/service/ClubServiceUnitTest.java
Labels: ✨ Feature, 🔨 Refactor

#72 feat/#67
  src/main/java/com/charmroom/charmroom/dto/business/ArticleDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/AttachmentDto.java
  src/main/java/com/charmroom/charmroom/dto/business/AttachmentMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/BoardDto.java
  src/main/java/com/charmroom/charmroom/dto/business/BoardMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentDto.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentLikeDto.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentLikeMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentMapper.java
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/entity/Comment.java
  src/main/java/com/charmroom/charmroom/service/ArticleService.java
  src/main/java/com/charmroom/charmroom/service/AttachmentService.java
  src/main/java/com/charmroom/charmroom/service/BoardService.java
  src/main/java/com/charmroom/charmroom/service/CommentLikeService.java
  src/main/java/com/charmroom/charmroom/service/CommentService.java
  src/test/java/com/charmroom/charmroom/service/ArticleServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/BoardServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/CommentLikeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/CommentServiceUnitTest.java
Labels: ✨ Feature, 🔨 Refactor

#79 Feat/#74 articlelike
  src/main/java/com/charmroom/charmroom/controller/api/AuthApiController.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleLikeDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleLikeMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/AttachmentDto.java
  src/main/java/com/charmroom/charmroom/dto/business/AttachmentMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/BoardDto.java
  src/main/java/com/charmroom/charmroom/dto/business/BoardMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/ClubDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ClubMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentDto.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentLikeDto.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentLikeMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/CommentMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/ImageDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ImageMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/PointDto.java
  src/main/java/com/charmroom/charmroom/dto/business/PointMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/UserDto.java
  src/main/java/com/charmroom/charmroom/dto/business/UserMapper.java
  src/main/java/com/charmroom/charmroom/dto/presentation/SignupDto.java
  src/main/java/com/charmroom/charmroom/entity/Article.java
  src/main/java/com/charmroom/charmroom/entity/ArticleLike.java
  src/main/java/com/charmroom/charmroom/entity/Club.java
  src/main/java/com/charmroom/charmroom/entity/Comment.java
  src/main/java/com/charmroom/charmroom/entity/User.java
  src/main/java/com/charmroom/charmroom/service/ArticleLikeService.java
  src/main/java/com/charmroom/charmroom/service/ArticleService.java
  src/main/java/com/charmroom/charmroom/service/AttachmentService.java
  src/main/java/com/charmroom/charmroom/service/BoardService.java
  src/main/java/com/charmroom/charmroom/service/ClubService.java
  src/main/java/com/charmroom/charmroom/service/CommentLikeService.java
  src/main/java/com/charmroom/charmroom/service/CommentService.java
  src/main/java/com/charmroom/charmroom/service/ImageService.java
  src/main/java/com/charmroom/charmroom/service/PointService.java
  src/main/java/com/charmroom/charmroom/service/UserService.java
  src/test/java/com/charmroom/charmroom/service/ArticleLikeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ArticleServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/BoardServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ClubServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/CommentLikeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/CommentServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/UserServiceUnitTest.java
Labels: ✨ Feature

#80 Feat/#75 wish service dto
  src/main/java/com/charmroom/charmroom/dto/business/WishDto.java
  src/main/java/com/charmroom/charmroom/dto/business/WishMapper.java
  src/main/java/com/charmroom/charmroom/service/WishService.java
  src/test/java/com/charmroom/charmroom/service/WishServiceUnitTest.java
Labels: ✨ Feature

#81 Feat/#76 subscribe dto
  src/main/java/com/charmroom/charmroom/dto/business/SubscribeDto.java
  src/main/java/com/charmroom/charmroom/dto/business/SubscribeMapper.java
  src/main/java/com/charmroom/charmroom/service/SubscribeService.java
  src/test/java/com/charmroom/charmroom/service/SubscribeServiceUnitTest.java
Labels: ✨ Feature

#82 Feat/#78 ad service dto
  src/main/java/com/charmroom/charmroom/dto/business/AdDto.java
  src/main/java/com/charmroom/charmroom/dto/business/AdMapper.java
  src/main/java/com/charmroom/charmroom/service/AdService.java
  src/test/java/com/charmroom/charmroom/service/AdServiceUnitTest.java
Labels: ✨ Feature

#83 Feat/#58 service dto
  src/main/java/com/charmroom/charmroom/dto/business/AdDto.java
  src/main/java/com/charmroom/charmroom/dto/business/AdMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleLikeDto.java
  src/main/java/com/charmroom/charmroom/dto/business/ArticleLikeMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/SubscribeDto.java
  src/main/java/com/charmroom/charmroom/dto/business/SubscribeMapper.java
  src/main/java/com/charmroom/charmroom/dto/business/WishDto.java
  src/main/java/com/charmroom/charmroom/dto/business/WishMapper.java
  src/main/java/com/charmroom/charmroom/entity/ArticleLike.java
  src/main/java/com/charmroom/charmroom/service/AdService.java
  src/main/java/com/charmroom/charmroom/service/ArticleLikeService.java
  src/main/java/com/charmroom/charmroom/service/SubscribeService.java
  src/main/java/com/charmroom/charmroom/service/WishService.java
  src/test/java/com/charmroom/charmroom/service/AdServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/ArticleLikeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/SubscribeServiceUnitTest.java
  src/test/java/com/charmroom/charmroom/service/WishServiceUnitTest.java
Labels: ✨ Feature
